name: pkg-test

on:
  push:
    tags:
      - "v*"
    paths-ignore:
      - "**.md"

jobs:
  run-test:
    runs-on: macos-latest

    steps:
      - name: Tap repository
        run: brew tap vrelease/formulas

      - name: Install vrelease
        run: brew install vrelease

      - name: Run vrelease (version)
        run: vrelease -v

      - name: Run vrelease (help)
        run: vrelease -h

